#! /bin/bash

set -e

printusage () {
    echo "usage: $0 (-b | -r) [-h]"
    echo "Very basic RPC tester."
    echo "  -b: Build everything"
    echo "  -r: Run example"
}

chdir () {
    cd `pwd`/$1
}

buildsdna () {
    printf "\e[1;32m#### Changing to sdna dir.\e[0m\n"
    chdir sdna
    printf "\e[1;32m#### Cleaning up before building.\e[0m\n"
    make clean
    printf "\e[1;32m#### Running 'autoreconf -i -f'.\e[0m\n"
    autoreconf -i -f
    printf "\e[1;32m#### Running './configure'.\e[0m\n"
    ./configure
    printf "\e[1;32m#### Running 'make'.\e[0m\n"
    make
}

buildsrpc () {
    printf "\e[1;32m#### Changing dir back.\e[0m\n"
    chdir ..
    printf "\e[1;32m#### Cleanin up first.\e[0m\n"
    make clean_all
    printf "\e[1;32m#### Building lib.\e[0m\n"
    make libservalrpc.a
    printf "\e[1;32m#### Building servalrpc.\e[0m\n"
    make
}

run () {
    printf "\e[1;32m#### Running example call.\e[0m\n"
    ./servalrpc call CB54C16A87E832F6AC87B396A2B3484A5200C5BD2DBB587F7B88C1942DEEDA09 add 1 2
}

if [ "$1" = "-b" ]; then
	buildsdna
    buildsrpc
elif [[ "$1" = "-r" ]]; then
    run
else
    printusage
fi
